# Generated by Django 5.2.2 on 2025-06-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=250)),
                ('lifting_capacity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sio2_percent', models.FloatField()),
                ('fe_percent', models.FloatField()),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polygon', models.TextField(default='POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))')),
                ('weight', models.IntegerField()),
                ('sio2_percent', models.FloatField()),
                ('fe_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('unload_time', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.truck')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
