# Generated by Django 5.2.2 on 2025-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='y_coord',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='weight_after_unload',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='weight_before_unload',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
