# Generated by Django 5.2.2 on 2025-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_truck_x_coord_remove_truck_y_coord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='overload',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
