# Generated by Django 5.2.2 on 2025-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_truck_overload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unload',
            name='x_coord',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unload',
            name='y_coord',
            field=models.FloatField(),
        ),
    ]
