# Generated by Django 5.2.2 on 2025-06-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_unload_x_coord_alter_unload_y_coord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='overload',
        ),
    ]
