# Generated by Django 5.2.2 on 2025-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_truck_overload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='weight_after_unload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='weight_before_unload',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
