# Generated by Django 5.2.2 on 2025-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_warehouse_weight_after_unload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
